server:
  port: 80


spring:
  application:
    name: cloud-comsumer-Consul-order
  cloud:
    consul: #consul地址
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}